####################################################################################
# Makefile (configuration file for GNU make - see http://www.gnu.org/software/make/)
#
# Author : Sebastien Varrette <Sebastien.Varrette@imag.fr>
#          Web page : http://www-id.imag.fr/~svarrett/
#
# Please refer to ../Makefile for more informations on compilation options
# Alternatively, you may try 'make help'
####################################################################################

all:
        make -C ../
%:
        make -C ../ $@
